VIP code review fixes
reaktivstudios/TimelineJS-Wordpress-Plugin pull request #1
Opened 2019-04-12 17:04 UTC by SolomonSScott

2019-04-17 18:31 UTC, SolomonSScott commented
@reaktivstudios/reviewers this is ready for review.

2019-04-19 17:39 UTC, corywebb requested changes
Just a couple of little things.

2019-04-19 17:39 UTC, corywebb commented on knightlab-timeline.php
> +	href='#TB_inline?width=600&height=495&inlineId={$container_id}'> Add Timeline</a>";
Needs i18n.

2019-04-19 17:39 UTC, corywebb commented on knightlab-timeline.php
> +		var font = jQuery('#timeline_font').val();
This section should be done with a single `var`.

2019-04-19 17:39 UTC, corywebb commented on knightlab-timeline.php
> +									<option value="zh-cn" data-lang="Chinese">中文</option>
All the `<option>` tags need 1 more tab.

2019-04-19 18:56 UTC, corywebb approved these changes
LGTM

2019-04-19 18:57 UTC, merged